### ISSUE TITLE
Return a Disposable from consumeOutlineProvider

### ISSUE THREAD

**Issue by lierdakil** [atom-community/atom-ide-outline#128]
https://github.com/atom-community/atom-ide-outline/blob/660a1263f267bf7d70a3787d7d2798f1611801a7/src/main.ts#L54-L64

Consumers _really_ should return a disposable (as discussed in https://github.com/TypeStrong/atom-typescript/pull/1587)

The only change needed here hopefully is saving the result of `subscriptions.add` and returning it.

Side note, I've created a custom tslint rule to catch unused disposables a while back, see here: https://www.npmjs.com/package/tslint-use-atom-disposables (I apparently forgot to publish the source code though; EDIT: published at https://github.com/lierdakil/tslint-use-atom-disposables)

**Comment by aminya** [comment]
Thanks for the issue. Since double freeing the disposable [doesn't cause issues](Atom-ide-outline manages its own memory internally. Is it fine to double free), it is fine to return it in the service too.

**Comment by lierdakil** [comment]
> Atom-ide-outline manages its own memory internally. Is it fine to double free

Not sure if I understand what you mean here. Calling `dispose()` on an already-disposed `Disposable` is [always a no-op](https://flight-manual.atom.io/api/v1.57.0/Disposable/#instance-dispose). Also, JS is garbage-collected. There's no manual memory management, so I'm not sure what you're referring to with "internal memory management".
