### ISSUE TITLE
Empty outline when initially opened

### ISSUE THREAD

**Issue by lierdakil** [atom-community/atom-ide-outline#94]
When the outline isn't opened by default, when initially opened, it's always empty. Need to switch active editor back and forth to populate it.

I've taken a quick look at the code, and I have some suggestions, architecture-wise, so that this kind of issue becomes pretty much impossible. However, this would entail a pretty major refactoring, so I'm asking if it's something I should even consider spending my time on (i.e. if a major refactoring is on the cards at all). Otherwise, I can make a quick (hacky) fix.

**Comment by aminya** [comment]
> I can make a quick (hacky) fix.

I am fine with refactoring as long as it doesn't introduce a performance regression. However, if it is possible to fix it in an easier way, then closing this issue would be just that. If you decided to rewrite the pane management, also take a look at #80.

Feel free to decide whichever that seems best.
