### ISSUE TITLE
Default .outline-icon custom

### ISSUE THREAD

**Issue by 73** [atom-community/atom-ide-outline#99]
Hi, 

I am doing a lot of LaTeX and Markdown. With text the default icon uses a lot of space where I would like to read the heading title:
![image](https://user-images.githubusercontent.com/529346/111141033-5187db00-8583-11eb-8bc3-10d8611cedb8.png)
Is is possible to change this, e.g., remove the default icon?

Thank you very much!

**Comment by aminya** [comment]
We are working on a PR for the next release that allows making the outline to take less space. So, for now, I am going to hold off on adding an option for hiding the icons.

**Comment by 73** [comment]
Thanks!

**Comment by aminya** [comment]
@73 Check out the new release and let me know what you think

**Comment by 73** [comment]
Well. Now it's dead :(
![image](https://user-images.githubusercontent.com/529346/111178393-624c4700-85ab-11eb-8c35-39f5416e16af.png)

**Comment by aminya** [comment]
The error was fixed in the recent version.

**Comment by 73** [comment]
I can not tell. I am on version 2.3.1 and I see the picture [shown above](https://github.com/atom-community/atom-ide-outline/issues/99#issuecomment-799511599).

**Comment by aminya** [comment]
Which ide-latex provider are you using? Could you share your settings for the outline?

**Comment by 73** [comment]
Thank you for getting back to me.

> Which ide-latex provider are you using?
None. I did not have to before. `atom-ide-outline` rendered an outline for LaTeX and Markdown out of the box. Do I have to install something specific now?

> Could you share your settings for the outline?
Sure. From my `config.cson`:
```cson
  "atom-ide-outline":
    foldInitially: true
    initialDisplay: false
```

**Comment by aminya** [comment]
Yes, there should be a provider that uses our service (not implementing their own outline tab). There is this package which uses our service. But not sure if it is working.

https://atom.io/packages/ide-latex

**Comment by 73** [comment]
I see. [ide-latex](https://atom.io/packages/ide-latex) is broken, so no luck there. 
If `atom-ide-outline` dont has a generic view, I am back to: https://atom.io/packages/document-outline
Thanks anyway!
